### ISSUE TITLE
Error in my SepiaIOwrapper, empty RDF

### ISSUE THREAD

**Issue by Emere123** [kschan0214/sepia#35] opened 2022-06-17 12:30 UTC
Hello! I have a question about the SepiaIOWrapper file. I get this error: 
performing polynomial fitting...There was an error! Please check the command window/error message file for more information.
Output argument "b" (and maybe others) not assigned during call to "PolyFit".

Error in BackgroundRemovalMacro (line 106)
        [~,RDF,~]   = PolyFit(double(RDF),maskLocalFiled,refine_order);

Error in SepiaIOWrapper (line 264)
localField = BackgroundRemovalMacro(totalField,maskLocalfield,matrixSize,voxelSize,algorParam,headerAndExtraData);

Error in sepiaIO (line 78)
    SepiaIOWrapper(input,output,maskFullName,algorParam);

My RDF is empty and my totalField also. I was wondering where this can go wrong, because my header and phase and mag data are valid according to the sepia guide.

**Comment by kschan0214** [comment] 2022-08-01 08:51
Hi! Sorry for the late reply. The error is likely caused by the empty total field map instead of the PolyFit function. Therefore, it means that there is something wrong during the total field map computation process. Can you please provide us (1) the pipeline configuration file (sepia_config.m), (2) the log file (run_sepia.log) and let us know which scanner was used for the data acquisition for diagnosis? Thanks

**Comment by kschan0214** [comment] 2023-10-17 05:31
I am closing this issue now because I have not yet receive any follow up. Please open a new issue if you encounter the same problem.

**Closed by kschan0214** 2023-10-17 05:31 UTC
